// ACCOUNT DATA
export const ACCOUNT_DATA_VALUE_CHANGE = 'ACCOUNT_DATA_VALUE_CHANGE';
export const ACCOUNT_DATA_CURRENCY_CHANGE = 'ACCOUNT_DATA_CURRENCY_CHANGE';

// CURRENCIES
export const CURRENCIES_GET_RATE_LOADING = 'CURRENCIES_GET_RATE_LOADING';
export const CURRENCIES_GET_RATE_SUCCESS = 'CURRENCIES_GET_RATE_SUCCESS';
export const CURRENCIES_GET_RATE_ERROR = 'CURRENCIES_GET_RATE_ERROR';
export const CURRENCIES_GET_ALL_SYMBOLS_LOADING = 'CURRENCIES_GET_ALL_SYMBOLS_LOADING';
export const CURRENCIES_GET_ALL_SYMBOLS_SUCCESS = 'CURRENCIES_GET_ALL_SYMBOLS_SUCCESS';
export const CURRENCIES_GET_ALL_SYMBOLS_ERROR = 'CURRENCIES_GET_ALL_SYMBOLS_ERROR';
